changelog:
  exclude:
    labels:
      - chore
      - test
      - ci
  categories:
    - title: Нове
      labels: [feature, enhancement]
    - title: Виправлення
      labels: [bug, fix]
    - title: Інше
      labels: ["*"] # catch-all for everything else
